name: Deploy Frontend AWS

on:
  push:
    branches: [main, master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build 

      - name: Login DockerHub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      
      - name: Build Docker Image
        run: docker build -t beatrizschindler/easynote_frontend_image .
       
      - name: Push image docker
        run: docker push beatrizschindler/easynote_frontend_image